### ISSUE TITLE
Cross-validation warning

### ISSUE THREAD

**Issue by ritisha2000** [UBC-MDS/drug_consumption_prediction#15]
I'm having an issue with the cross-validation. Since there are some target columns that have some classes that appear only twice or only a few times, cross-validation complains about doing more splits than that. I'm not sure how to avoid that warning. 

![image](https://user-images.githubusercontent.com/35882817/204071005-a4a05688-b876-4eba-8094-249f4445d588.png)

**Comment by shaunhutch** [comment]
I was just looking into this, I saw a stack overflow article that discussed this problem. I think we could use stratify = y in the test_train_split. This stratify parameter makes a split so that the proportion of values in the sample produced will be the same as the proportion of values provided to parameter stratify.

I don't know if that would for sure fix the issue, but thought it could be worth a try

The other option could be that we pick another drug (which seems like it would be breaking the golden rule) or use cv = 2, but then maybe less reliable

**Comment by shaunhutch** [comment]
Resolved, closing issue
